#!/bin/sh

# This script is intended to be run by farmout's cmsRun.sh in "fwklite" mode.
# It runs on the worker node and merges root files into one file.

if [ -z "${INPUT}" ] || [ -z "${OUTPUT}" ]; then
  echo "Expected INPUT and OUTPUT to be defined in the environment." 1>&2
  exit 2
fi

if ! [ -f "${INPUT}" ]; then
  echo "Cannot find file pointed to by INPUT: ${INPUT}" 1>&2
  exit 1
fi

exec hadd "${OUTPUT}" `cat ${INPUT}`
